defmodule Calculationsbugrepro.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cart_items) do
      add(
        :cart_id,
        references(:cart_items,
          column: :id,
          name: "cart_items_cart_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:cart_items, "cart_items_cart_id_fkey"))

    alter table(:cart_items) do
      remove(:cart_id)
    end
  end
end
